
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE IF NOT EXISTS authors (
    id BIGINT PRIMARY KEY,
    name VARCHAR NOT NULL,
    age DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    isbn VARCHAR PRIMARY KEY,
    title VARCHAR NOT NULL,
    author_id BIGINT NOT NULL REFERENCES authors(id)
);